version: '3.8'

services:
  ian-pichost:
    build: .
    container_name: ian-pichost
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
      
    networks:
      - ian-pichost-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=ian-pichost"
      - "com.docker.compose.service=ian-pichost"

networks:
  ian-pichost-network:
    driver: bridge

volumes:
  uploads:
    driver: local
  logs:
    driver: local
